spring:
  application:
    name: ecommerce

  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/ecommerce}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:hourkk12}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false

server:
  port: 8081
app:
  jwt:
    secret-key: fjaskhdfalskfhlaksfhlaksfa123456
    expire-seconds: 864400
cloudflare:
  r2:
    account-id: cc78e3f856c6792852fa53557bda3676
    access-key: 6b1f42c18ccd1756a8aef22f9f3911e8
    secret-key: fa63959a8bd24619c53fa01b3e890bcf54138ee1b879f1b5d01f8d393491a22d
    bucket: uploadimage