spring:
  application:
    name: ecommerce

  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/ecommerce}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:hourkk12}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false

server:
  port: 8081
  server: 0.0.0.0
app:
  jwt:
    secret-key: fjaskhdfalskfhlaksfhlaksfa123456
    access-expire-seconds:  604800
    refresh-expire-seconds: 604800
cloudflare:
  r2:
    account-id: cc78e3f856c6792852fa53557bda3676
    access-key: 6b1f42c18ccd1756a8aef22f9f3911e8
    secret-key: fa63959a8bd24619c53fa01b3e890bcf54138ee1b879f1b5d01f8d393491a22d
    bucket: uploadimage
    public-url: https://pub-62c73c1bf764486499dac7b7a08c5820.r2.dev
bakong:
  account-id: bunhour_ti@bkrt
  base-url: https://api-bakong.nbc.gov.kh/
  email: tibunhour@gmail.com
  token-Bakong: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlkIjoiZjE3YjVlOTNhM2UzNDNhMSJ9LCJpYXQiOjE3ODYyNTkwNDMsImV4cCI6MTc5NDAzNTA0M30.DfqTZ3oR2C2Bl4ExojjhEOwYaj_-on8GgMR_X6uTb7M

aba:
  base-url: https://checkout-sandbox.payway.com.kh/
  merchant-id: ec478445
  api-key: 05f69d4dad9c3e52416f493a17340a085f1de0e1